### ISSUE TITLE
Proposal: Bi-weekly working session

### ISSUE THREAD

**Issue by edsadr** [openjs-foundation/ecosystem-report-collab-space#1]
Hello everybody,

I hope this message finds you well. As we embark on our new collaboration space, it's crucial that we establish a regular cadence for this initiative to ensure effective communication and progress. Given the distributed nature of our members located in both Europe and America, I propose that we set up a biweekly sync to accommodate everyone's time zones and schedules. and to give people time to accommodate their calendars I would suggest starting the week of April 22 – April 26

**Proposed Meeting Frequency**: Biweekly (every two weeks)

**Suggested Time Slots**:

To accommodate the time difference between Europe and America, I suggest the following time slots for our bi-weekly meetings:

Option 1: 7:00 AM PDT, 10:00 AM EDT, / 4:00 PM CEST
Option 2: 8:00 AM PDT, 11:00 AM EDT, / 5:00 PM CEST
Option 3: 9:00 AM PDT, 12:00 PM EDT, / 6:00 PM CEST

I also created a Doodle for all of you to mark your availability:

https://doodle.com/meeting/participate/id/bkORVoxb

I look forward to your participation and any feedback here.

**Comment by anfibiacreativa** [comment]
Hi @edsadr , thanks for putting this up.

Should we make it easier to vote, mapping the times to reactions? 
Also, do you propose a specific day? The availability may be day dependent, too.

I suggest Thursdays, then my vote would be Option2.

**Comment by edsadr** [comment]
hey @anfibiacreativa , the idea is to use the doodle in this URL: https://doodle.com/meeting/participate/id/bkORVoxb  to mark everyone's availability. Please take some time and set all possible options for you there

**Comment by anfibiacreativa** [comment]
> hey @anfibiacreativa , the idea is to use the doodle in this URL: https://doodle.com/meeting/participate/id/bkORVoxb to mark everyone's availability. Please take some time and set all possible options for you there

I see. however options are Mon, Weds and Fridays only, which are all entirely blocked for me.

**Comment by edsadr** [comment]
@anfibiacreativa please mark your availability in the doodle no matter the current options, we can accommodate later, In the meantime, let's wait for @tobie , @PaulaPaul , @mhdawson and @italojs to reply here

**Comment by italojs** [comment]
hi all,  
 I'm free every day for those options, my vote is for option 1 but I'm fine with any option if someone can attend at option 1
